language: cpp

services:
  - docker

matrix:
  include:
    - env: ARCH=x86_64
    - env: ARCH=i386

script:
  - bash -xe travis/build-appimage.sh

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh linuxdeploy-plugin-appimage*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
